### ISSUE TITLE
下个版本更新大概在2018年3月份左右

### ISSUE THREAD

**Issue by lsamu** [lsamu/data_collection#3]
下个版本更新大概在2018年3月份左右

**Comment by Pinkuburu** [comment]
好哥哥还更新吗，我2010年，2011年的工作还用火车头采集器的，看到这个项目很亲切

**Comment by lsamu** [comment]
有需要就更新

**Comment by Pinkuburu** [comment]
作者更新一波吧……都鸽了一年了23333，求更新学习

**Comment by lsamu** [comment]
再等等吧 我手上有个项目要处理 可以加我qq 83112223
